import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import tempfile

st.set_page_config(page_title="AI Data Analyst", layout="wide")

st.title("AI Data Analyst + Smart Report Generator")

file = st.file_uploader("Upload Excel / CSV", type=["xlsx","csv"])

if file:

    # READ FILE
    if file.name.endswith(".csv"):
        df = pd.read_csv(file)
    else:
        df = pd.read_excel(file)

    st.header("Dataset Preview")
    st.dataframe(df)

    numeric_cols = df.select_dtypes(include=["int64","float64"]).columns
    cat_cols = df.select_dtypes(include=["object"]).columns

    if len(numeric_cols) == 0:
        st.error("No numeric column found")
        st.stop()

    target = numeric_cols[0]

    # BASIC STATS
    st.header("Basic Statistics")

    avg = round(df[target].mean(),2)
    mx = df[target].max()
    mn = df[target].min()

    c1,c2,c3 = st.columns(3)

    c1.metric("Average",avg)
    c2.metric("Max",mx)
    c3.metric("Min",mn)

    # HISTOGRAM
    st.header("Distribution")

    fig_hist, ax = plt.subplots()
    df[target].hist(ax=ax)

    st.pyplot(fig_hist)

    charts = []
    insights = []

    # CATEGORY ANALYSIS
    st.header("Category Analysis")

    for col in cat_cols:

        if df[col].nunique() < 20:

            grp = df.groupby(col)[target].mean()

            fig, ax = plt.subplots()
            grp.plot(kind="bar", ax=ax)

            ax.set_title(f"{target} by {col}")

            st.pyplot(fig)

            charts.append((fig,f"{target} by {col}"))

            best = grp.idxmax()
            worst = grp.idxmin()

            best_val = round(grp.max(),2)
            worst_val = round(grp.min(),2)

            explanation = f"""
Analysis for {col}:

• {best} performs the best with an average value of {best_val}.
This indicates stronger performance compared to other {col} categories.

• {worst} shows the lowest value of {worst_val}, suggesting weaker contribution.

Possible reasons:
- market demand difference
- operational efficiency
- customer preference variation

Recommendation:
Focus on replicating strategies from {best} while improving operations or marketing in {worst}.
"""

            insights.append(explanation)

    # PIE CHARTS
    st.header("Category Distribution")

    for col in cat_cols:

        if df[col].nunique() < 10:

            counts = df[col].value_counts()

            fig, ax = plt.subplots()
            counts.plot(kind="pie", autopct="%1.1f%%", ax=ax)

            ax.set_title(col)
            ax.set_ylabel("")

            st.pyplot(fig)

            charts.append((fig,f"{col} Distribution"))

    # SMART INSIGHTS
    st.header("Smart Business Insights")

    st.write(f"Average {target} across dataset is **{avg}**")

    for i in insights:
        st.write(i)

    # --------------------------
    # POWERPOINT GENERATOR
    # --------------------------

    if st.button("Generate Professional PowerPoint"):

        prs = Presentation()

        # TITLE SLIDE
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)

        slide.shapes.title.text = "Business Data Analysis Report"
        subtitle = slide.placeholders[1]
        subtitle.text = "Auto Generated by AI Analyst"

        # STATS SLIDE
        slide = prs.slides.add_slide(prs.slide_layouts[1])

        slide.shapes.title.text = "Key Statistics"

        text = f"""
Average Value : {avg}

Maximum Value : {mx}

Minimum Value : {mn}
"""

        slide.placeholders[1].text = text

        # INSIGHTS SLIDES
        for insight in insights:

            slide = prs.slides.add_slide(prs.slide_layouts[1])

            slide.shapes.title.text = "Business Insight"

            slide.placeholders[1].text = insight

        # CHART SLIDES
        for fig,title in charts:

            tmp = tempfile.NamedTemporaryFile(delete=False,suffix=".png")
            fig.savefig(tmp.name)

            slide = prs.slides.add_slide(prs.slide_layouts[5])

            slide.shapes.title.text = title

            slide.shapes.add_picture(
                tmp.name,
                Inches(1),
                Inches(1.5),
                height=Inches(4.5)
            )

        ppt_path = "analysis_report.pptx"
        prs.save(ppt_path)

        with open(ppt_path,"rb") as f:

            st.download_button(
                "Download PowerPoint Report",
                f,
                file_name="business_analysis_report.pptx"
            )
